### ISSUE TITLE
[Bug] Typewriter Scrolling not working

### ISSUE THREAD

**Issue by hyuri** [story-apps/starc#100]
"Use typewriter scrolling" is enabled but not working.

#### App Info
- Starc v0.5.0a (Flatpak)

#### System Info
- Pop!_OS 22.04
- X11

**Comment by dimkanovikov** [comment]
In what of concrete module typewriter scrolling is not working for you? Did you check it with a document that has text more than half of the screen?

**Comment by hyuri** [comment]
It isn't working in the Screenplay module, in the screenplay document.

The document is 17 pages long.

**Comment by hyuri** [comment]
Just checked the dev-build and the issue is still happening.

**Comment by dimkanovikov** [comment]
Hm... can you please provide a screen recording with demonstration? Since I can't reproduce this issue so far.

**Comment by hyuri** [comment]
https://user-images.githubusercontent.com/18584014/235894000-c5daa2b2-70d7-4968-b1af-005aafbcaad2.mp4

**Comment by dimkanovikov** [comment]
Typewriter scrolling place the cursor at the center of the screen only when you write, not when you move it around the text (since it leads to multiple issues and annoying scrolling when you move the cursor with the mouse, or want to select some part of the text etc.).

**Comment by hyuri** [comment]
Oh, can we make it a feature request to make typewriter work when we scroll the page as well? That's how the typewriter mode works in WriterDuet, so I got used to it.

**Comment by dimkanovikov** [comment]
But what is the reason? Why do you think this kind of behavior useful?

**Comment by hyuri** [comment]
2 reasons:

### Reason 1
Because there's no point in moving the text cursor around if you're not gonna do anything with it. In the current way, the text cursor only moves freely if you don't change the text. If you move your cursor around (freely), the moment you change any text, such as typing, deleting, adding space, etc., it activates the typewriter scroll and scrolls the page.

So let's say you moved your cursor all the way up and deleted a word, it will activate the typewriter scroll, the page will scroll up and your eyes will have to move from the top to the center.

If the cursor is always in the center, your eyes don't have to move so much. And that's how typewriters work: you always scroll the page, not the cursor. The "cursor" is always in the center, not just when typing.

Example from WriterDuet/WriterSolo:


https://user-images.githubusercontent.com/18584014/236699924-27b5d2ba-3d9b-4c96-8d80-b86d6750b7d3.mp4




### Reason 2
Also, it's useful to be able to scroll the page without taking your hands off the keyboard.

But for this one, specifically, it's better to have a dedicated feature, where we can scroll the page without moving the cursor, so I would like to re-recommend implementing this suggestion I made a year ago: dimkanovikov/KITScenarist#963

**Comment by dimkanovikov** [comment]
Okay, let's try to expand typewriter scrolling to all keyboard events, not only writing.

**Comment by dimkanovikov** [comment]
Implemented in the latest dev-version

**Comment by hyuri** [comment]
Awesome! Works great. Thank you!
