### ISSUE TITLE
[Bug] Importing KIT Scenarist Project not working properly

### ISSUE THREAD

**Issue by hyuri** [story-apps/starc#103]
Imported KIT Scenarist projects have the text in KIT Scenarist's scene descriptions imported into the scene body instead of the "Description" field of Scene Parameters, messing the whole scene.

Another issue:
Importing KIT Scenarist project only imports the first Act/folder (and the 2 scenes contained in it)

#### App Info
- Starc v0.5.0a (Flatpak)

#### System Info
- Pop!_OS 22.04
- X11

**Comment by dimkanovikov** [comment]
Can you please provide a sample KIT Scenarist file which led to this issue?

**Comment by hyuri** [comment]
I can't share the project I'm working on right now, but I'll see if can reproduce the problem with another project and share that one.

**Comment by hyuri** [comment]
Another issue:
Importing KIT Scenarist project only imports the first Act/folder (and the 2 scenes contained in it)

**Comment by dimkanovikov** [comment]
So, can you please provide a minimal reproducible example for both issues?

**Comment by hyuri** [comment]
https://user-images.githubusercontent.com/18584014/235894000-c5daa2b2-70d7-4968-b1af-005aafbcaad2.mp4

**Comment by hyuri** [comment]
Here we go:
[Test Story.zip](https://github.com/story-apps/starc/files/11381744/Test.Story.zip)

And a screenshot of the resulting imported screenplay:
![Screenshot from 2023-05-03 07-49-05](https://user-images.githubusercontent.com/18584014/235896773-5a4d7449-8ef9-4bc7-9437-7167bfeae221.png)

**Comment by dimkanovikov** [comment]
Thank you! Issue with importing multiple acts fixed. But what about description of folders/scenes, I need to think about how to implement it in a most elegant way.

**Comment by hyuri** [comment]
Nice. Thanks!

For descriptions, I think they should just go in the "Description" field of "Scene Parameters". Different writers will use that description field for different purposes — some for beats, some for work-in-progress ideas — but if we're importing from KIT Scenarist, I think the expectation is that what was in the description field in KIT Scenarist should go in the description field of Starc.

I noticed if I copy text with multiple lines from the description field of a scene in a KIT Scenarist project and paste it in the description field in Starc, the text is broken down into multiple description fields, paragraph by paragraph. That was actually pretty useful.

**Comment by dimkanovikov** [comment]
@david-wendelken please, check it out with version 0.5.2 (which was released yesterday)

**Comment by david-wendelken** [comment]
At first glance, it's now working correctly.  Haven't double-checked it at the detail level, but at least all the acts and scenes are present.

**Comment by dimkanovikov** [comment]
scene descriptions importing was implemented
