### ISSUE TITLE
how do I quit the program?

### ISSUE THREAD

**Issue by alan12345678** [story-apps/starc#108]
just successfully installed starc-appimage from AUR. Set up fine, but I can't find out how to quit the app? None of the expected commands work (I'm using i3).

**Comment by dimkanovikov** [comment]
I don't know how it looks like in Arch, but does the app's window title bar invisible here? 

As a workaround, you always can use standard shortcuts for closing the app `Ctrl+F4`, `Ctrl+Q`, or `Ctrl+Shift+Q`

**Comment by alan12345678** [comment]
Indeed there is no window title bar. This is because I've disabled them in my WM. However, the "$mod+shift+q" quits it - as I found out after further experimentation.

But there's nothing resembling a menu, and which would normally (in the absence of anything else) contain a "quit application" option.

If I have to continue with the key combo then fine, just wanted to make you aware. LOVELY app, btw :)

**Comment by dimkanovikov** [comment]
Thanks. We discuss inside the team a lot about should the app waste the space and concentration of the user to such a standard things like close the app menu item, or zoom in/out buttons... I'm personally vote for removing (or avoid of adding) all things that can be handled via some sort of standard shortcut, or similar way.

**Comment by alan12345678** [comment]
Fair enough. I suppose I was only thrown because having used my setup for several years now the only keys ever necessary to close have been "$mod+q" or "$mod+w". The few apps I do use that don't respect those keys have their own "quit" as a menu option.

Completely on board with not wasting screen space. That said, as a desktop user, a toolbar wouldn't upset me, more particularly if it were switchable (e.g. the menu option on a browser via F10 or F11). I like that it's so straightforward, but that said its total simplicity can leave one wanting the familiar comfort of a toolbar where everything is visible in one place, at a glance. All just personal prefs of course :)

**Comment by dimkanovikov** [comment]
It's a good idea to add support of the "$mod+q" shortcut. It will be available in the next update.
