### ISSUE TITLE
[Bug] Act lengths not matching total sum of scenes' lengths

### ISSUE THREAD

**Issue by hyuri** [story-apps/starc#118]
![image](https://github.com/story-apps/starc/assets/18584014/91f36b37-4e3c-4a78-b06b-690e4628ebd9)

In the screenshot:
Act | 2:10
Scene | 1:58
Act | 4:30
Scene | 4:24
Act | 1:10
Scene | 1:04

**Comment by dimkanovikov** [comment]
It's absolutely expected, since act header and title use some part of the page.

**Comment by hyuri** [comment]
Ah, I see. Any way to hide act-related lines before calculating?

**Comment by dimkanovikov** [comment]
You have two options here:
- don't use page based duration calculation
- remove acts :)

I don't really think that avoiding of these 6 seconds per act can be so much helpful.

**Comment by hyuri** [comment]
I surely do, but what's the point of having these features if I should avoid using them?

6 seconds * acts is not a big deal, it just confuses and looks wrong. But if it's too hard to implement, forget about it.

**Comment by dimkanovikov** [comment]
Counting duration based on pages place us in a some rules and if we'll break this rules nothing good happens. If you'll add any text lines to the page, be ready to it will be counted as a part of script duration (of act, or scene, or beat, etc).

**Comment by hyuri** [comment]
Yeah, forget about it. If it's complicated, it's not worth it.
