### ISSUE TITLE
[Feature Request] Rename "Scene Parameters" to "Properties"

### ISSUE THREAD

**Issue by hyuri** [story-apps/starc#122]
Rename "Scene Parameters" to "Properties", so that it better fits in smaller screens, and doesn't get cut like it does now:

![image](https://github.com/story-apps/starc/assets/18584014/c20c007f-abb1-49e5-bd81-b07b623eebc6)

**Comment by dimkanovikov** [comment]
This make name not so concrete - Parameters of what?

**Comment by dimkanovikov** [comment]
No, bookmarks page show you bookmarks from the entire document.

What about showing character info on selecting character name, in my opinion, this is not intuitive to user.

**Comment by hyuri** [comment]
Right.

But, in any case, the name is still too long for smaller screens. Game engines and other creative apps (like Blender) have a "Properties" panel that presents properties for whatever is selected, so that doesn't seem unclear to me. But what about "Scene" or "Scene Info"?
