### ISSUE TITLE
[Bug] Mess after pressing backspace on line that says "END OF ACT 1" and undoing

### ISSUE THREAD

**Issue by hyuri** [story-apps/starc#123]
After pressing backspace on/erasing the line that says "END OF ACT 1" and undoing (Ctrl + Z), the document turned into this mess, where the random text I had in the scene's description got copied into the screenplay document.

![image](https://github.com/story-apps/starc/assets/18584014/99cf428e-aad9-4c91-8f2f-71ba8cc66cab)

**Comment by dimkanovikov** [comment]
I can't reproduce it on the current state of the app.
