### ISSUE TITLE
[Bug] Keyboard navigation broken in the "Add Bookmark" dialog

### ISSUE THREAD

**Issue by hyuri** [story-apps/starc#133]
When I click the "Add Bookmark" option and the "Add Bookmark" dialog shows up where I can name the bookmark and choose a color:
Pressing `Tab` a few times takes the focus out of the dialog, and `Shift + Tab` doesn't bring it back.

Also, `Tab` doesn't change focus to the color button, it just takes the focus out of the dialog.

**Comment by dimkanovikov** [comment]
This one is fixed
