### ISSUE TITLE
[Feature Request] Add a separator between bookmarks in the BOOKMARKS panel

### ISSUE THREAD

**Issue by hyuri** [story-apps/starc#138]
### Problem
There is no separation between bookmarks in the BOOKMARKS panel, so it's hard to know which text belongs to which bookmark, especially when looking at a glance, especially if they have the same color.

![image](https://github.com/story-apps/starc/assets/18584014/83ebc6be-036e-479b-943a-7a195aa196ee)

### Proposal
Add a separator between bookmarks, such as a thin line/border.

![image](https://github.com/story-apps/starc/assets/18584014/599a6c55-6ec7-4fc7-90b7-b683ba5cf883)

**Comment by dimkanovikov** [comment]
Can you please attach the screenshot with demonstration? Basically, margins and icons should do the job about different items identification.

**Comment by hyuri** [comment]
Attached.

**Comment by dimkanovikov** [comment]
Ah, got it, thanks! I didn't remember why we decided to avoid icons in this list... looks like if we'll show an icon with each bookmark, this list becomes more self-explainable and consistent with other lists.

**Comment by dimkanovikov** [comment]
It's fixed in the current dev-version.
