### ISSUE TITLE
[Feature Request] Make draft locking wording clearer

### ISSUE THREAD

**Issue by hyuri** [story-apps/starc#140]
### Problem
In the Edit draft dialog, the wording "Allow to edit draft" is confusing. Especially because it is located in the "Edit draft" dialog — seems related to the Edit draft dialog.

And especially because it is toggled off by default even though a draft should be editable by default. We create a new draft so we can work on improvements, a new pass. First Draft, Second Draft, Third Draft, etc., all the way to the elusive Final Draft.

### Proposal
I propose to change it to "Lock editing", inverting the meaning, and make it toggled off by default so we can press "Create" and start editing it right away as expected. And then later we can come back and lock it if we want.

**Comment by dimkanovikov** [comment]
Good idea. It's implemented in the following dev-version.
