### ISSUE TITLE
[Feature Request] Add support for importing screenplays in PDF

### ISSUE THREAD

**Issue by hyuri** [story-apps/starc#152]
It would be handy if we could import a PDF file. Starc would try its best to interpret the text — almost treating it like Fountain —, and then the user can do manual adjustments if necessary.

This is useful in 2 cases:
1. Converting old screenplays only available in PDF
2. When we want to use Starc to load a screenplay only available in PDF, for reading, rewriting (for educational purposes), or adding notes (bookmarks). This is particularly useful when studying (that often requires reading screenplays only available in PDF)

**Comment by dimkanovikov** [comment]
This one was implemented in the last release.
