### ISSUE TITLE
Why is the editing area so tiny?

### ISSUE THREAD

**Issue by kanwarplaha** [story-apps/starc#153]
As shown in the below screenshot, the editing area / pages are tiny. 
I have chosen page size as A4 and text size around 12-14 pts. 
This is on Kubuntu 23.04 and I've adjusted Qt settings using qt5ct.
Running on X11, not Wayland.

![Screenshot_20230802_143855](https://github.com/story-apps/starc/assets/62160679/d1c764ab-6d63-440d-81eb-0649a924db67)

**Comment by dimkanovikov** [comment]
Wow! It's really weird thing... Does the synopsis, outline and text has similar issue? Can you try to add plain text document to the project and check is this issue related to it too?

**Comment by kanwarplaha** [comment]
Yes, happy to help test it though. After chat on Facebook, I tried the
screenplay module too, and notice the same tiny editing widgets, both for
flatpak and AppImage.

**Comment by kanwarplaha** [comment]
Has this been addressed in 0.6.1? Thanks.

**Comment by dimkanovikov** [comment]
So, I installed vanilla Kubuntu 23.04 and seems issue is not reproduced. Can you please share what settings you tweaked with the qt5ct tool?

**Comment by kanwarplaha** [comment]
Hello, thanks for your reply.

My qt5ct config file is attached.

I upgraded to Starc 0.6.2 and the same issue persists:
[image: Screenshot_20231018_181903.png]

**Comment by dimkanovikov** [comment]
Hi! Looks like attaching files to the email replies didn't work for GitHub issues... I can't find any attachments to your last message.

**Comment by dimkanovikov** [comment]
Hi @kanwarplaha any updates on this issue?

**Comment by kanwarplaha** [comment]
Hello,

This appears to have been resolved in recent versions.

Thank you,
Kanwar

**Comment by dimkanovikov** [comment]
nice, thanks for update
