### ISSUE TITLE
[Bug] Automatic character completion adds new line before existing dialogue block immediately after

### ISSUE THREAD

**Issue by hyuri** [story-apps/starc#154]
### Issue
If I have an existing block of dialogue without character name — which is common when I split a big block of dialogue into two and add an action line in-between them —, when I add a character name before this block of dialogue, by choosing one of the options the automatic character completion provides, and press Enter, Starc adds the name but also areturns/adds a new line after the name, in-between the name and the nameless dialogue after.

### Suggestion
Starc should detect that there already is dialogue or parentheticals in the next line, and should avoid returning/adding a new line in that case.

**Comment by dimkanovikov** [comment]
To avoid adding a new line after choosing items in the dropdown hints, you can use Tab button.
