### ISSUE TITLE
[Suggestion] Use Title Case for the whole UI

### ISSUE THREAD

**Issue by hyuri** [story-apps/starc#181]
### Issue
Right now, Starc uses Sentence case, where it only capitalizes the first letter of a sentence. Like **Screenplay navigator**. This looks unprofessional, careless.
![image](https://github.com/story-apps/starc/assets/18584014/f672a6b3-f082-4221-bd46-242999552fa8)

### Proposal
I propose to use Title Case, where the first letter of every major word is capitalized, like **Screenplay Navigator**. It looks more professional, more polished, more carefully and intentionally crafted. Exceptions are minor words such as "of", "a", etc.

For reference, that's what Apple uses for their UI, and the AP for their headlines.

**More info on Title Case:**
https://en.wikipedia.org/wiki/Title_case

**Comment by dimkanovikov** [comment]
This was our decision to use sentence case, since it’s much more friendly for reading and mostly recommended to use by UX experts for modern apps.

**Comment by hyuri** [comment]
Got it.

I'd still like to emphasize that Title Case is what Apple and many other big names use, and, Apple in particular is seen as a gold standard in design.

**Comment by dimkanovikov** [comment]
Yeah, I know it, thanks. We made a big research and decided to use mostly friendly for users approach.
