### ISSUE TITLE
[Bug] Text editor zoomed out too much

### ISSUE THREAD

**Issue by RyanGlade** [story-apps/starc#194]
When going into the text editor it seems to be zoomed out to much, attached screenshot so its easier to see what I mean

![Capture](https://github.com/story-apps/starc/assets/93811191/aaac9d41-4bbd-49c4-a518-864c60361bd8)

**Comment by dimkanovikov** [comment]
Hi, you can use Ctrl+ shortcut or Ctrl with mouse wheel for zoom in.

**Comment by RyanGlade** [comment]
Thanks
