### ISSUE TITLE
[Bug] Scene colours missing in editor scrollbar in version 0.6.0

### ISSUE THREAD

**Issue by KsenoJiva** [story-apps/starc#195]
### Issue
In the current version the scene colours are no longer displayed on the scrollbar.

![image](https://github.com/story-apps/starc/assets/29759497/cc69f155-d250-41a5-8f07-722434274449)

As you can see only the very last scene's colour is visible in the scrollbar.

Very rarely it fixed itself in previous versions. But in 0.6.0 I no longer get it to work. Tried reloading, different stories, opening from File, opening from stories tab, recolouring. Nothing works.

### Expectations
The scene colours should appear along the scrollbar scaled to their respective size.

I'd really appreciate a fix for that as it makes navigating around so much easier as well as giving a visual clue of the pacing.

**Comment by dimkanovikov** [comment]
Hi @KsenoJiva,

Thanks for the report. Can you please share this file with us via email support@starc.app? And we'll check what's can be wrong with scenes colors.

**Comment by KsenoJiva** [comment]
> Hi @KsenoJiva,
> 
> Thanks for the report. Can you please share this file with us via email [support@starc.app](mailto:support@starc.app)? And we'll check what's can be wrong with scenes colors.

Done. I hope you find the issue.

**Comment by dimkanovikov** [comment]
Yes, thank you very much. It's [fixed](https://github.com/story-apps/starc/commit/5f639ebc52eef4a73ad9035ea7aaf20311f96646) for the next dev-version 0.6.1 dev 15. It will be built approx in 40 minutes.

**Comment by KsenoJiva** [comment]
Awesome. Thank you for the fast fix.
The colours are back again 😄
