### ISSUE TITLE
The saved files size only grow

### ISSUE THREAD

**Issue by damluishl** [story-apps/starc#198]
Hi,
I noticed that when you remove all the text of the script and save the file, the file size doesn't reduce.
I wrote a 40 pages script and its size is around 8 MB.
Am I doing something wrong?

**Comment by dimkanovikov** [comment]
Hey,

This is because STARC project file is not only a container for project data/text, it's a database, and it also stores inside all changes you have made since you start work on this project. 

You even can open this project and undo last action.

So, this is by design.

**Comment by damluishl** [comment]
Ok, didn't know that. Thanks!
