### ISSUE TITLE
[Bug] Export excluding sequence headers and footers messes up page breaks

### ISSUE THREAD

**Issue by KsenoJiva** [story-apps/starc#201]
I like to use acts and sequences to structure my writing.
But in the final exported PDF I do not want them, so on export I use the option "Exclude sequence headers and footers".

### Issue

On exporting a screenplay with acts and sequences,  with the option "Exclude sequence headers and footers" enabled, the automatic page breaks shift upward from the actual end of the page.

_In STARC_
![image](https://github.com/story-apps/starc/assets/29759497/c2bdbd8f-490e-4cd0-93b1-3117287d500f)

_In PDF_
![image](https://github.com/story-apps/starc/assets/29759497/202b6a52-e533-4b47-b022-9596a987219d)

### Expectation

The automatic page breaks should be recalculated on export according to the to be exported script layout.

**Comment by dimkanovikov** [comment]
Hello,

Thanks! It should be fixed in the latest dev version. Please check it when you'll have a time.

**Comment by KsenoJiva** [comment]
Again, thank you for the quick fix.

The automatic page breaks are now correctly placed in the exported PDF.
