### ISSUE TITLE
Remove Period From Scene Number

### ISSUE THREAD

**Issue by MitchWoodin** [story-apps/starc#209]
Hi,

This may be something unique to me so feel free to ignore. But I want to have scene numbers shown but with the period after the numbers it feels off balance. Maybe I'm just use to seeing the numbers without the period so I can't unsee them. Is it possible to at least be given the option to remove the dots? 

Thanks,
Mitchell

**Comment by dimkanovikov** [comment]
Hello Mitchell,

Yes you can configure scene numbers template and add period after number. [Here](https://starc.app/blog/2022-11-30) you can find more details about how to configure scene numbers template.

**Comment by MitchWoodin** [comment]
![image](https://github.com/story-apps/starc/assets/42667068/8a8e0f7b-d2da-491e-8e59-3e9e83cdd4b0)
I don't see the option that is shown on that page. Am I looking in the wrong place? I've also looked in the settings but can't find it anywhere?

**Comment by MitchWoodin** [comment]
Never mind I found the settings section in the top left of the window! Thanks
