### ISSUE TITLE
screenplay formatting 

### ISSUE THREAD

**Issue by j215chic** [story-apps/starc#272]
I can't seem to find ( in the Linux image) a place to check the formatting of a screenplay.  I think the industry format is as below BUT my script doesn't seem to conform to it.  What am I missing please?

The industry standard font and layout for a screenplay is highly specific:

    Font: 12-point Courier (or Courier New)
        This font is used because it creates consistent page length, with one page roughly equating to one minute of screen time.

    Page size: 8.5" x 11" (US Letter)

    Margins:
        Left margin: 1.5 inches
        Right margin: 1 inch
        Top margin: 1 inch
        Bottom margin: 1 inch

 

    Line spacing: Single-spaced within elements, but double-spaced between them (e.g., between action and dialogue).

**Comment by dimkanovikov** [comment]
You can find them in the menu - application settings - screenplay - template - create new template based on current.

**Comment by dimkanovikov** [comment]
![image](https://github.com/user-attachments/assets/961e1edd-613d-49c0-8b67-bc571305b365)

**Comment by dimkanovikov** [comment]
More details can be found in [this](https://starc.app/help/custom-templates) article.

**Comment by dimkanovikov** [comment]
Custom templates stored in the app directory, but you can save and load them via interface option. The app has several default templates, which are compatible with different standards (for example, US template compatible with the Hollywood requirements).
