### ISSUE TITLE
Don't collapse multiple spaces in a row

### ISSUE THREAD

**Issue by Koopa1018** [story-apps/starc#53]
Trying to make a SERIES OF SHOTS, which is formatted as a list. As the online screenwriting tools all suggest, I want to manually indent every line of the list to start after the bullet point:
```
SERIES OF SHOTS - FINBAR TO THE EMPLOYMENT OFFICE - DAY
- INT. TREY'S KITCHEN - Trey's fridge is less than half full.
  Finbar stares at it, deep in thought.
- EXT. EMPLOYMENT OFFICE - A small yet official-looking
  building. Finbar steps out of traffic and up the steps to
  the front door.
END SERIES OF SHOTS
```

Unfortunately this is not possible, because KIT Scenarist only shows a single space regardless of how many space characters there are:
```
SERIES OF SHOTS - FINBAR TO THE EMPLOYMENT OFFICE - DAY
- INT. TREY'S KITCHEN - Trey's fridge is less than half full.
Finbar stares at it, deep in thought.
- EXT. EMPLOYMENT OFFICE - A small yet official-looking
building. Finbar steps out of traffic and up the steps to the
front door.
END SERIES OF SHOTS
```

(This includes spaces on the previous line, by the way.)

Please let us control our formatting!

**Comment by dimkanovikov** [comment]
Hello, my friend.

Thank you for the suggestion. We'll add it to the Story Architect.

**Comment by dimkanovikov** [comment]
added since v 0.0.10
