### ISSUE TITLE
AppImage fails to display dropdown menu

### ISSUE THREAD

**Issue by LazyKitKat** [story-apps/starc#60]
**Distro:** Pop!_OS 21.10
When clicking on a dropdown menu it just blinks and disappears. 
It happens with all dropdown menus, whether it be when creating a new story or in settings menu.

**Comment by dimkanovikov** [comment]
Should be fixed with [0.1.1](https://github.com/story-apps/starc/releases/download/v0.1.1/starc-setup.AppImage)

**Comment by LazyKitKat** [comment]
The crashing itself is fixed, however, dropdown menus still do not show up upon clicking. Scrolling with arrows works as intended.

**Comment by LazyKitKat** [comment]
My bad, I wasn't checking out the newer version. It's fixed now.
