### ISSUE TITLE
Сборка бесплатной версии с заявленным функционалом из открытых источников.

### ISSUE THREAD

**Issue by aaly11** [story-apps/starc#61]
Привет.
Можно ли будет собрать, когда-либо, бесплатную версию программы со всеми перечисленными для этой версии возможностями из открытых источников, как то:
✔ Неограниченное количество проектов
✔ Неограниченное количество документов в проекте
✔ Конструктор постера
✔ Папки
✔ Текстовые документы
ПЕРСОНАЖИ
✔ Базовое досье
ЛОКАЦИИ
✔ Базовое описание
СЦЕНАРИИ
✔ Логлайн и синопсис
✔ Титульная страница
✔ Текст поэпизодника
✔ Текст сценария
✔ Базовая статистика
✔ Импорт/экспорт
КОМИКСЫ
✔ Логлайн и синопсис
✔ Титульная страница
✔ Текст сценария
✔ Базовая статистика
✔ Импорт/экспорт
**Часть проекта (src/cloud) закрыта.**
Пока что, для Персонажей - базовое досье и Локаций - базовое описание, ответ такой: "Ой... похоже редактор для этого документа ещё не реализован."
Корзина, Сценарий - поэпизодник и статистика, Комикс - статистика, также "ещё не реализованы".
Проекты на Open Build Service:
[Deb&RPM-based](https://build.opensuse.org/package/show/home:AndnoVember:KITScenarist/starc)
[Flatpak](https://build.opensuse.org/package/show/home:AndnoVember:KITScenarist:Flatpak/starc)

**Comment by dimkanovikov** [comment]
Привет!

Из этого списка в Open Source не попадут базовые описания персонажей/локаций и статистика. Они реализованы в закрытых плагинах, но доступ к ним будет открыт. Остальные модули будут включены в этот репозиторий по мере их реализации.
