### ISSUE TITLE
Pasting into Treatment editor is very broken

### ISSUE THREAD

**Issue by Koopa1018** [story-apps/starc#64]
Currently, pasting text into the Treatment editor (multiple lines, either from Notepad or from KIT Scenarist) appears to do nothing, but in fact silently puts the pasted text in the Screenplay.

Additionally, after pasting into an empty Treatment (no scenes), I can no longer click to put my cursor in the Treatment editor. When I attempt to use Select All to put the cursor back into the treatment editor, the cursor does not visibly reappear, and typing makes the program crash. (There was a time when typing worked, but it crashed when I went to the Screenplay editor.)

After a crash, the Treatment editor remains impossible to select in the document in question (not in others though), but the program no longer crashes after Select All and typing.

In addition, adding scene headers via the Screenplay editor seems to circumvent the glitch by putting selectable text in the Treatment editor.

**Comment by dimkanovikov** [comment]
Thanks for the report! I'll check it ASAP

**Comment by dimkanovikov** [comment]
Should be fixed in the `0.1.5 dev 69` build.
