### ISSUE TITLE
Can't line-break a beat in half

### ISSUE THREAD

**Issue by Koopa1018** [story-apps/starc#65]
For some odd reason, in the Treatment editor, pressing Enter only adds a new beat when the cursor is _at the end of the current beat._ If I press it at any earlier character, nothing happens (including if there's a trailing space--very inconvenient).

I would expect pressing Enter mid-line to split the beat in two at the cursor.

**Comment by Koopa1018** [comment]
Keep text from before the cursor in beat 1, and move text from after into beat 2.

**Comment by dimkanovikov** [comment]
I mean another thing :)

Beat can have a part of the screenplay text (it can be one paragraph or many), and when you split beat, what we should do with this text?

But for now, I think that all beat contents should stay with a first part of the separated beat.

**Comment by Koopa1018** [comment]
Ahhh.

Yes, I agree.

**Comment by Koopa1018** [comment]
What. But. Scene headings and beats are not the same at all. Splitting a scene heading in half is a strange thing to do anyway, but splitting off a sentence from a beat that's too long is perfectly normal to want to do. Moving the content of the first beat into the second will make the program feel badly behaved.

**Comment by dimkanovikov** [comment]
Yes, I was wrong, but you're right. Remastering it. So, now content should stay in the first part of separated beat. You can check it in the latest dev-version.
