### ISSUE TITLE
Deleting off the end of audioplay dialogue deletes entire line

### ISSUE THREAD

**Issue by Koopa1018** [story-apps/starc#67]
Testing out audioplays, I found that when the cursor is at the end of a dialogue line, pressing the DELETE key will delete the entire current line, including the character name.

I would've expected this to delete _just_ the next character in the _next_ line--I regularly use this to pull the next line into the dialogue (by deleting the line break), and it's weirding me out that I can't do this.

EDIT: This only happens when the dialogue is attached to a character. Loose dialogue, as is created when pasting screenplay text into an audioplay, behaves as expected.

**Comment by dimkanovikov** [comment]
I see minimum one corner case which not fit to this flow. If there are two dialogues from different characters in a row, and user press delete button at the end of the first dialogue. How the app should act in this case?

**Comment by Koopa1018** [comment]
Yeah, I noticed that case also....

Given the following case:
```
BEN	I like capes.|
DAN	I hate fire trucks.
>>
```

There are three ways I might handle pressing delete here.

- Pull in _both_ the next character and the next dialogue, so that all text is preserved. Other text editors behave this way, including the Screenplay editor and non-Starc programs, so I would consider this my ideal case.
```
BEN	I like capes.|DAN I hate fire trucks.
>>
```
- Pull in _just_ the next dialogue and remove the next character, potentially helpful when transferring dialogue between characters.
```
BEN	I like capes.| I hate fire trucks.
>>
```
- Ignore the keystroke and leave the document unchanged. Not ideal because the user will expect deletion to do something.
```
BEN	I like capes.|
DAN	I hate fire trucks.
>>
```

**Comment by Koopa1018** [comment]
Huh! I didn't think of moving the cursor to the next line. That's an interesting behavior that I think has merit!
