### ISSUE TITLE
Clicking between lines jumps to last created beat

### ISSUE THREAD

**Issue by Koopa1018** [story-apps/starc#69]
Ordinarily, clicking blank space between or outside lines in a document should jump the cursor to the nearest line.
But in a Screenplay with multiple Treatment beats defined, clicking blank space anywhere above the final beat in the Screenplay editor jumps the cursor to the start of the final beat, even if the final beat is several pages away.
This does not occur for blank space after the final beat, nor does it occur when clicking directly on the text of lines.

EDIT: I just realized, I haven't been able to test except for beats _within sequences._ This may be necessary to reproduce the bug.

**Comment by dimkanovikov** [comment]
Fixed.

Will be available via dev-build, when [job](https://github.com/story-apps/starc/actions/runs/2421835853) finished.
