### ISSUE TITLE
Beats added in Treatment fail to show in Screenplay

### ISSUE THREAD

**Issue by Koopa1018** [story-apps/starc#70]
When I create many beats in the Treatment editor, only the final created beat shows in the Screenplay.
![image](https://user-images.githubusercontent.com/29995463/168716767-f7afe4ef-5944-4cd7-b6d9-112d335dbf3a.png)

This even extends to beats created in previous scenes! If I add three beats in each scene, only the last beat _in the last scene_ shows:
![image](https://user-images.githubusercontent.com/29995463/168717121-3b478ba0-e1e8-4aaf-973b-6eaadc732e98.png)

**Comment by dimkanovikov** [comment]
This one should be fixed in the current dev-version. Please check it.

**Comment by Koopa1018** [comment]
How do I access dev-versions?

**Comment by Koopa1018** [comment]
Huh. In-app updates seems like an odd feature to restrict to users with accounts, but who am I to judge? ¯\_(ツ)_/¯

**Comment by Koopa1018** [comment]
I guess I'm just generally not fond of creating accounts I don't need.
(Once there's realtime collaboration, and I have someone to collab with,
then gladly, but until then it seems rather pointless.)
