### ISSUE TITLE
Act headings in Screenplay editor

### ISSUE THREAD

**Issue by Koopa1018** [story-apps/starc#71]
Currently, Starc's only way to break up acts of a television story is using Sequences. These work for drafting, but they don't match American formatting standards. 

I propose that a new line type, _Act,_ be added to the Screenplay editor (and probably also Treatment editor).

The most essential behavior of an Act is that **an Act header is always the first thing on a page.** It will jump ahead and leave the previous page mostly blank if it needs to.

Aside from this, the way I envision Acts is mostly exactly the same as Sequences--they count as folders, and optionally end with text reading "END OF _____". Ideally, Acts should not be able to nest within each other--when an Act is created in the middle of another Act, the folder ought to split in two

The text of an act header is underlined, and is justified to the page center. I can't find whether this applies to the footer as well; more research is required.

EDIT: A rough mockup of what I'm thinking:
![image](https://user-images.githubusercontent.com/29995463/172118865-2b5cabc3-2e7f-406c-b08f-e4d4677a9846.png)

**Comment by dimkanovikov** [comment]
Thanks! Yeah. This one is on the plan for one of the nearest updates.

**Comment by dimkanovikov** [comment]
Hello, my friend! This one implemented! Can be checked in the current dev-version.

One thing I decided to put off for later is an act breaking when a user adds a new act inside another act. I try to implement it, but it requires a lot of changes in the folder-like items handling, so decide to skip it right now.

**Comment by Koopa1018** [comment]
That seems fair
