### ISSUE TITLE
Contributing to starc development

### ISSUE THREAD

**Issue by 8byr0** [story-apps/starc#77]
Do you have any plan to open this project to external contributors? 

It is now not possible to run it locally due to the plugins behind closed source repos. 

I understand that opening this part would make unlockable the pro features for anyone building the project but as far as I know it could be possible to provide development binaries for these parts isn't it?

**Comment by dimkanovikov** [comment]
It should be able to build and run without these proprietary plugins and cloud service integration part. I'll check it, thanks!

**Comment by 8byr0** [comment]
After seeing they were not available i did not investigate any further TBH.

For the cloud service you could create a mocking API (like what stripe provides for unit testing https://github.com/stripe/stripe-mock).

**Comment by dimkanovikov** [comment]
We're having a bit less resources than stripe XD

But I fixed the open source part, and now it should build and work without any problems (and without proprietary plugins, of course).
