### ISSUE TITLE
Text is typed at the beginning of last 'Scene Heading' line

### ISSUE THREAD

**Issue by RonYanDaik** [story-apps/starc#80]
After switching several times the type of line text stops being appeared at caret when typed  ans instead letters appearing at beginning or end of last SCENE HEADING line.

Win 10. 
v 0.4.1

**Comment by RonYanDaik** [comment]
Afters some tests looks like it does not depends from `Scene Heading`. If  `Scene Heading` is missing text will be typed at start of current line.
![typing bug](https://user-images.githubusercontent.com/3350340/217880871-9550f7da-4e53-48c3-bd2f-b105ed1134e8.gif)

**Comment by RonYanDaik** [comment]
Another typing issue - sometimes app does not react to ENTER or CTRL+[NUM] keys or etc. Only to letter keys.

**Comment by RonYanDaik** [comment]
Don't have exact way to reproduce:
Switching between tabs, switching between line types, adding removing lines in 'treatment' tab.

**Comment by dimkanovikov** [comment]
Thank you! This issue was reported by other users also, but I still can't find a way to reproduce it...

**Comment by dimkanovikov** [comment]
This one is fixed
