### ISSUE TITLE
On cloning project gives error and 'qbreakpad' can't be cloned.

### ISSUE THREAD

**Issue by RonYanDaik** [story-apps/starc#81]
After cloning 'qbreakpad' folder is empty and has to be copied manually from repository.

win 10.

**Comment by RonYanDaik** [comment]
And after copying it manually I've got this error:

`:-1: error: No rule to make target 'D:/SomePath/starc/src/3rd_party/qbreakpad/third_party/breakpad/src/client/windows/crash_generation/crash_generation_client.cc', needed by '_build/obj/crash_generation_client.o'.  Stop.`

**Comment by RonYanDaik** [comment]
`:-1: error: No rule to make target 'D:/YurasGarbage/GitHubRepos/starc/src/3rd_party/qbreakpad/third_party/breakpad/src/client/windows/crash_generation/crash_generation_client.cc', needed by '_build/obj/crash_generation_client.o'.  Stop.`

**Comment by RonYanDaik** [comment]
`:-1: error: No rule to make target 'D:/SomePath/starc/src/3rd_party/qbreakpad/third_party/breakpad/src/client/windows/crash_generation/crash_generation_client.cc', needed by '_build/obj/crash_generation_client.o'.  Stop.`

**Comment by dimkanovikov** [comment]
looks like you need to use command to pull submodules

`git submodule update --recursve`

**Comment by dimkanovikov** [comment]
@RonYanDaik Did you check it?

**Comment by RonYanDaik** [comment]
I'm not using console, but i've never had issues with submodules before. This is what i get from GitHub Desktop

![image](https://user-images.githubusercontent.com/3350340/218672701-65666e01-dd00-43c9-8a81-e300997bd53f.png)

TartoiseGit

![image](https://user-images.githubusercontent.com/3350340/218673510-70070a8d-faf1-4c4e-8992-7986409bcdba.png)
![image](https://user-images.githubusercontent.com/3350340/218673536-1826d905-3837-411c-9a8e-e2ecb0a74cb2.png)
![image](https://user-images.githubusercontent.com/3350340/218675502-a12b33a5-a4cc-44ed-81f2-a4b3623c016f.png)

Submodule update:
![image](https://user-images.githubusercontent.com/3350340/218675878-ddf3a26c-9302-4fff-863f-a47e2efaa6a7.png)


Maybe it tries to access privet directories, fails and then fails at everything else

**Comment by dimkanovikov** [comment]
Did you clone repository with https or ssh session?

**Comment by RonYanDaik** [comment]
> Did you clone repository with https or ssh session?

HTTPS

**Comment by dimkanovikov** [comment]
Now it should be fixed, please check it again
