### ISSUE TITLE
[Feature Request] Ability to set automatic custom style of text (color, boldness etc) for line types.

### ISSUE THREAD

**Issue by RonYanDaik** [story-apps/starc#84]
For example user wants to make SCENE HEADING yellow and bold to see it more clearly, CHARACTER as cyan, and etc.

**Comment by dimkanovikov** [comment]
You can configure font style (typeface, bold, italic, underline, strikeout, alignment etc.) via custom templates in settings. But what about colors - we forbid it to be changed since it will be conflicted with the review mode highlights (and with revision mode in future).
