### ISSUE TITLE
[Bug] New screenplay project contains scene parameters from the previous project

### ISSUE THREAD

**Issue by hyuri** [story-apps/starc#85]
Hi!

1. I created a screenplay project, importing a KIT Scenarist file;
3. The KIT Scenarist project didn't import correctly, with acts, scenes and scene parameters all wrong, so I deleted the project;
4. I then created a new fresh screenplay project;
5. Went to the Screenplay page, the "SCENE PARAMETERS" panel was filled with text from the previous, just-deleted project.

After saving the project, closing it and opening it again, the text from the previous project is gone.

### App & System Info
- Starc v0.5.0a (Flatpak)
- Pop!_OS 22.04
- X11

**Comment by dimkanovikov** [comment]
Clearly a bug. Will be fixed.

**Comment by dimkanovikov** [comment]
Fixed. Will be included in the next dev-build.
