### ISSUE TITLE
[Bug] Cursor set changes when it enters the app window

### ISSUE THREAD

**Issue by hyuri** [story-apps/starc#89]
The cursor set changes when it enters the app window. It does not use the system's cursors.

### Before
![image](https://user-images.githubusercontent.com/18584014/234509869-dfc4d2f1-b9f5-4d20-b7a7-4b4efa71b779.png) ![image](https://user-images.githubusercontent.com/18584014/234510656-f0364ab3-698b-446c-8dba-65280ae74104.png)

### After
![image](https://user-images.githubusercontent.com/18584014/234509859-cd1175a1-c7b9-48f5-a4cd-eb85ffdeac19.png) ![image](https://user-images.githubusercontent.com/18584014/234510632-bcd88ed5-a027-48ab-a4ba-b2f0c61514f0.png)

#### Expectation:
The cursors should remain unchanged, following the system setting.

#### App Info
Starc v0.5.0a (Flatpak)

#### System Info
Pop!_OS 22.04
X11

**Comment by dimkanovikov** [comment]
What desktop environment do you use?

**Comment by hyuri** [comment]
Gnome 42

**Comment by hyuri** [comment]
Just checked the dev-build (AppImage) and the issue doesn't happen there. May be something to do with Flatpak?

**Comment by dimkanovikov** [comment]
Yes, looks like an issue with Flatpak package. I'll check it.

**Comment by joshua-stone** [comment]
The latest build should have the permissions for proper cursor setting:

```
$ flatpak info --show-permissions dev.storyapps.starc
[Context]
shared=network;ipc;
sockets=x11;wayland;pulseaudio;
devices=dri;
filesystems=xdg-documents;

[Environment]
XCURSOR_PATH=/run/host/user-share/icons:/run/host/share/icons
```

**Comment by hyuri** [comment]
Working. Thank you!
