### ISSUE TITLE
[Bug] A "loading" red spinning wheel keeps running forever, even after closing the app and opening it again

### ISSUE THREAD

**Issue by hyuri** [story-apps/starc#90]
This "loading" red spinning wheel keeps running forever, no matter what I do.

![image](https://user-images.githubusercontent.com/18584014/234511534-806b09f8-e043-41a0-89a8-97db309c6f9d.png)

Is it because Starc can't connect to the internet? I like keeping my writing computer disconnected from the internet.

#### App Info
- Starc v0.5.0a (Flatpak)

#### System Info
- Pop!_OS 22.04
- X11

**Comment by dimkanovikov** [comment]
Yes, it's because of it can't connect to our server.

**Comment by hyuri** [comment]
I would suggest not displaying the icon or trying to connect to the server in offline sessions. I'm not connected to the cloud or collaborating with other writers, so it shouldn't be trying to connect to the internet.

**Comment by RonYanDaik** [comment]
What for its trying to connect to server if you're not logged in?

**Comment by dimkanovikov** [comment]
It's just trying to connect to the server when the application started, for no concrete reason... But it's a good idea, to connect to server only when user logging or already logged.

**Comment by dimkanovikov** [comment]
This thing was improved. For now, after one minute of the inactive connection red spinning indicator changed to gray disconnected icon.
