### ISSUE TITLE
[Feature] Cards should be available in Treament

### ISSUE THREAD

**Issue by hyuri** [story-apps/starc#94]
Cards should be available in Treament as well, as it's mostly used during that stage of development or during outlining (some people prefer doing outlines, some prefer doing treatments, some do both, although treatments are usually used to sell scripts).

Outlining, or "carding" when done using cards, basically serve the same purpose and are mostly used during the development of the story, the "breaking" of the story, when putting the story together, before the screenplay. Not necessarily as much during the actual writing of the screenplay.

**Comment by dimkanovikov** [comment]
Good idea! Thanks.

**Comment by dimkanovikov** [comment]
This one is implemented and available since version 0.5.4
