### ISSUE TITLE
[Feature] Make Shift + Scroll Wheel scroll horizontally

### ISSUE THREAD

**Issue by hyuri** [story-apps/starc#96]
It would be nice. It's especially useful with tabs like "Scene Parameters" and "Bookmarks" that don't quite fit in smaller screens.

Shift + Scroll Wheel horizontally scrolls by default [at least it does on Linux/Gnome].

#### App Info
- Starc v0.5.0a (Flatpak)

#### System Info
- Pop!_OS 22.04
- X11

**Comment by dimkanovikov** [comment]
Do you mean `Alt + Scroll Wheel`? As I see, it works just fine in the Starc under Linux.

`Shift + Scroll`  should make scroll faster.
