### ISSUE TITLE
[Bug] Clicking on a scene in the Screenplay Navigator does not change the selected scene in Scene Parameters

### ISSUE THREAD

**Issue by hyuri** [story-apps/starc#97]
Hi!

Clicking on a scene in the Screenplay Navigator doesn't change the selected scene in Scene Parameters. It only changes if you then click on the page afterwards.

It's very confusing because, my intuition is to click on a scene in the Screenplay Navigator and immediately start changing its parameters in the Scene Parameters. But when I do that now, I'm actually inadvertently editing the Scene Parameters of a previous scene. And when I realize that, it's too late and I've actually messed with the previous scene's parameters.

Might be connected with #85

**Comment by dimkanovikov** [comment]
This one should be fixed now. Please check it via the latest [dev-build](https://starc.app/downloads/dev/starc-setup.AppImage).

**Comment by hyuri** [comment]
Just checked. It is fixed in the dev-build indeed!
