### ISSUE TITLE
[Bug] Crash when pressing Enter on a Description field in the Scene Parameters

### ISSUE THREAD

**Issue by hyuri** [story-apps/starc#98]
Hi!

When I add some text to a Description field in the Scene Parameters and press Enter, Starc crashes.

This is what I see in the terminal:
```
2023.04.26 22:00:00.297 [D] Failed to write minidump, dump path: ~/Library/Containers/app/dev.storyapps.starc/data/Story Apps/Story Architect/crashreports/6f08e729-4f52-48e0-571770be-b0bb7deb.dmp

/app/bin/starc-run: line 2:     3 Segmentation fault      (core dumped) /app/bin/starc/starc $@
```

#### App Info
- Starc v0.5.0a (Flatpak)

#### System Info
- Pop!_OS 22.04
- X11

**Comment by dimkanovikov** [comment]
I can't reproduce this crash. Does it happen with each scene or with concrete one? Can you try to reproduce it with the latest dev-version?

**Comment by dimkanovikov** [comment]
@hyuri can you please recheck it with the latest version 0.5.1?

**Comment by hyuri** [comment]
Just checked. Doesn't seem to be happening on 0.5.1 for me anymore.

**Comment by dimkanovikov** [comment]
Nice, thanks for checking.
