### ISSUE TITLE
[Bug] Undo/Redo sometimes doesn't undo/redo all the steps and text disappear

### ISSUE THREAD

**Issue by hyuri** [story-apps/starc#99]
Sometimes doing a few undo and redo will make text disappear. I've had two of my parentheticals disappear.

#### App Info
- Starc v0.5.0a (Flatpak)

#### System Info
- Pop!_OS 22.04
- X11

**Comment by dimkanovikov** [comment]
Does this issue have some stable way to reproduce it?

**Comment by hyuri** [comment]
No, I tried a few more times but it hasn't happened again. It only seems to happen with text I copy from KIT Scenarist.

**Comment by dimkanovikov** [comment]
Hm... thanks for addition, will try to reproduce it.

**Comment by dimkanovikov** [comment]
This one is closed since we have no more similar reports.
